# -*- coding: utf-8 -*-
{'name': 'Multi Store for Warehouse',
 'version': '13.0.1.2.0',
 'category': 'Accounting',
 'sequence': 14,
 'summary': '',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'website': 'https://esibolivia.store',
 'license': 'AGPL-3',
 'images': [],
 'depends': ['stock', 'base_multi_store'],
 'data': ['views/stock_picking_type_view.xml',
          'views/stock_picking_view.xml',
          'views/stock_warehouse_view.xml',
          'views/res_store_view.xml',
          'security/multi_store_security.xml',
          'views/product_template.xml'],
 'demo': ['demo/stock_demo.xml'],
 'test': [],
 'installable': True,
 'auto_install': True,
 'application': False,
 'maintainer': 'ESI - Especialistas en Sistemas Integrados'}
