{'name': 'ESI - Tipo de Compras por Sucursal',
 'version': '13.0.1.0.0',
 'summary': 'Integra Tipo de Compras con Multi Store',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'maintainer': 'ESI - Especialistas en Sistemas Integrados',
 'website': 'https://esibolivia.store',
 'category': 'Purchase',
 'depends': ['esi_bi_automated_purchase_order',
             'esi_purchase_multi_store',
             'esi_stock_multi_store',
             'esi_account_multi_store'],
 'data': ['views/automated_purchase_store_views.xml'],
 'installable': True,
 'auto_install': True,
 'application': False,
 'license': 'LGPL-3'}
