{'name': 'ESI - Multi Stores Management',
 'version': '13.0.1.3.0',
 'category': 'Accounting',
 'sequence': 14,
 'summary': '',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'website': 'https://esibolivia.store',
 'license': 'AGPL-3',
 'images': [],
 'depends': ['base'],
 'data': ['security/ir.model.access.csv',
          'security/multi_store_security.xml',
          'views/res_store_view.xml',
          'views/res_users_view.xml'],
 'demo': ['demo/res_store_demo.xml'],
 'installable': True,
 'auto_install': False,
 'application': True,
 'maintainer': 'ESI - Especialistas en Sistemas Integrados'}
