{'name': 'ESI - Tipo de Ventas por Sucursal',
 'version': '13.0.1.1.0',
 'summary': 'Integra Tipo de Ventas con Multi Store',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'maintainer': 'ESI - Especialistas en Sistemas Integrados',
 'website': 'https://esibolivia.store',
 'category': 'Sales',
 'depends': ['esi_bi_automated_sale_order', 'esi_sale_multi_store', 'esi_stock_multi_store', 'esi_account_multi_store'],
 'data': ['views/automated_sale_store_views.xml'],
 'installable': True,
 'auto_install': True,
 'application': False,
 'license': 'LGPL-3'}
