{'name': 'ESI - Multi Store on Payment Groups',
 'version': '13.0.1.2.0',
 'category': 'Accounting',
 'sequence': 14,
 'summary': '',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'website': 'https://esibolivia.store',
 'license': 'AGPL-3',
 'images': [],
 'depends': ['account', 'esi_base_multi_store', 'esi_account_multi_store', 'account_payment_group'],
 'data': ['views/account_payment_group_views.xml', 'views/res_store_view.xml'],
 'demo': [],
 'installable': True,
 'auto_install': False,
 'application': False,
 'maintainer': 'ESI - Especialistas en Sistemas Integrados'}
