# -*- coding: utf-8 -*-
{'name': 'Multi Store for Accounting',
 'version': '13.0.1.3.0',
 'category': 'Accounting',
 'sequence': 14,
 'summary': '',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'website': 'https://esibolivia.store',
 'license': 'AGPL-3',
 'images': [],
 'depends': ['account', 'base_multi_store'],
 'data': ['views/account_journal_views.xml',
          'views/account_move_line_views.xml',
          'views/account_move_views.xml',
          'views/account_payment_views.xml',
          'views/res_store_views.xml',
          'security/multi_store_security.xml'],
 'demo': [],
 'installable': True,
 'auto_install': True,
 'application': False,
 'maintainer': 'ESI - Especialistas en Sistemas Integrados'}
